# railway.toml

# Define a single service for the BossCraft backend
[service]
name = "boss-craft-backend"

# Force the use of Docker to build the app
builder = "docker"

# Specify that the Dockerfile is located in the BossCraft subdirectory
[build]
dir = "BossCraft"

# Set environment variables
[env]
# The master password for the Odoo instance
ADMIN_PASSWORD = { from = "secret", name = "ADMIN_PASSWORD" }
# Database connection (these will be automatically populated if you have a linked PostgreSQL service)
DB_HOST = { from = "service", name = "postgresql", property = "host" }
DB_PORT = { from = "service", name = "postgresql", property = "port" }
DB_USER = { from = "service", name = "postgresql", property = "user" }
DB_PASSWORD = { from = "service", name = "postgresql", property = "password" }
DB_NAME = "odoo"
