# railway.toml

# Define the service for your BossCraft backend
[service]
name = "boss-craft-backend"
# This is the critical line: it forces the use of Docker
builder = "docker"

# Specify the build directory where your Dockerfile is located
[build]

# Define environment variables
[env]
ADMIN_PASSWORD = { from = "secret", name = "ADMIN_PASSWORD" }
