# railway.toml

# Define your backend service
[[services]]
name = "boss-craft-backend"
# Force the use of Docker and your Dockerfile
builder = "docker"
# Specify that the code is in the BossCraft subdirectory
[build]
dir = "BossCraft"

# Define your PostgreSQL database service
[[services]]
name = "postgres"
image = "postgres:15"
# Expose the database port
ports = [{ port = 5432 }]
# Set a default database name
[env]
POSTGRES_DB = "odoo"

# (Optional) Set a secret for the Odoo master password
[env]
ADMIN_PASSWORD = { from = "secret", name = "ADMIN_PASSWORD" }
